title: Just Biome
description: Just biome is a bedrock Minecraft addon focused on exploration and biomes.

remote_theme: carlosperate/jekyll-theme-rtd

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Abcdavk
repo_url: 'https://github.com/abcdavk/abcdavk'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
